server:
  port: 8120
spring:
  profiles:
    active: dev
  application:
    name: service-sms

  #spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 8
        min-idle: 0

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos??
  #spring:
  rabbitmq:
    host: 192.168.66.11
    port: 5672
    virtual-host: /
    username: leellun
    password: 123456

aliyun:
  sms:
    region-id: cn-hangzhou
    key-id: LTAI4G5Svnb2TWBMuKnNT6jY
    key-secret: N7v6R4V3EJ1SGDZlsqtqo8QyVVMmtQ
    template-code: SMS_96695065
    sign-name: ??

feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 60000
  sentinel:  #??Feign?Sentinel???
    enabled: true

logging:
  level:
    com.newland.srb.sms.client.CoreUserInfoClient: DEBUG
